# Generated by Django 3.2.8 on 2024-02-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='description',
            new_name='descripcion',
        ),
    ]
